import { createTheme } from '@mui/material/styles';

//NOTE:
//Theme overrides / modification / customization adapted largely from:
//https://mui.com/material-ui/customization/palette/
//https://mui.com/material-ui/customization/theme-components/


//Perform module augmentation in order to add some custom properties to the theme
declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    pageTitle?: true
    pageSubtitle?: true
  }
}

declare module '@mui/material/styles' {
  interface Palette {
    tertiary: Palette['primary'];
  }

  interface PaletteOptions {
    tertiary?: PaletteOptions['primary'];
  }
}

//Instantiate theme; adding in the custom color properties
//In this case, adding neutral and tertiary color to the palette
const neutralMain = '#000033' //https://www.shadegenerator.com/000033
const neutralDark = {
  0: '#000033',
  1: '#00002e',
  2: '#000029',
  3: '#000024',
  4: '#00001f',
  5: '#00001a',
  6: '#000014',
  7: '#00000f',
  8: '#00000a',
}

const neutralLight = {
  0: '#d9d9e0',
  1: '#bfbfcc',
  2: '#a6a6b8',
  3: '#8c8ca3',
  4: '#73738f',
  5: '#59597a',
  6: '#404066',
  7: '#262652',
  8: '#0d0d3d',
}

const tertiaryMain = '#FFCD4B'  //https://www.shadegenerator.com/FFCD4B
const tertiaryDark = {
  0: '#FFF8E4',
  1: '#FFEEC0',
  2: '#FFE49C',
  3: '#FFDA78',
  4: '#FFD054',
  5: '#CCA43C',
  6: '#997B2D',
  7: '#66521E',
  8: '#33290F',
}

const tertiaryLight = {
  0: '#FFF8E4',
  1: '#FFEEC0',
  2: '#FFE49C',
  3: '#FFDA78',
  4: '#FFD054',
  5: '#CCA43C',
  6: '#997B2D',
  7: '#66521E',
  8: '#33290F',
}


let themeBase = createTheme({
  palette: {
    mode: 'light',
    neutral: { 
      main: neutralMain,
    },
    primary: {  //https://www.shadegenerator.com/C2CFFF
      main: '#c2c2fff',
      dark: {
        0: '#f6f8ff',
        1: '#eaeeff',
        2: '#dde5ff',
        3: '#d1dbff',
        4: '#c5d1ff',
        5: '#9ba6cc',
        6: '#747c99',
        7: '#4e5366',
        8: '#272933',
      },
      light: {
        0: '#f6f8ff',
        1: '#eaeeff',
        2: '#dde5ff',
        3: '#d1dbff',
        4: '#c5d1ff',
        5: '#9ba6cc',
        6: '#747c99',
        7: '#4e5366',
        8: '#272933',
      },
    },
    secondary: {  //https://www.shadegenerator.com/FE7777
      main: '#fe7777',
      dark: {
        0: '#FFEBEB',
        1: '#FFCFCF',
        2: '#FEB4B4',
        3: '#FE9999',
        4: '#FE7E7E',
        5: '#CB5F5F',
        6: '#984747',
        7: '#663030',
        8: '#331818',
      },
      light: {
        0: '#FFEBEB',
        1: '#FFCFCF',
        2: '#FEB4B4',
        3: '#FE9999',
        4: '#FE7E7E',
        5: '#CB5F5F',
        6: '#984747',
        7: '#663030',
        8: '#331818',
      },
    },
    tertiary: {  
      main: '#ffcd4b',
    },
    background: {
      default: '#000033',
      paper: '#ffffff',
    },
    text: {
      primary: '#000033',
    },
  }
})

//Update the theme with the autogenerated dark/light/contrasttext colors for the tertiary palette
themeBase = createTheme(themeBase, {
  palette: {
    neutral: themeBase.palette.augmentColor({
      color: {
        main: neutralMain,
        dark: neutralDark,
        light: neutralLight
      },
      name: 'neutral'
    }),
    tertiary: themeBase.palette.augmentColor({
      color: {
        main: tertiaryMain,
        dark: tertiaryDark,
        light: tertiaryLight
      },
      name: 'tertiary'
    })
  }
})

//Add custom component styling
const SparrowLight = createTheme({
  palette: themeBase.palette,
  typography: {
    fontFamily: '"Karla", sans-serif',
    fontSize: 16,
  },
  components: {
    MuiTypography: {
      styleOverrides: {
        root: {
        }
      },
      defaultProps: {
        variantMapping: {
          //Add mapping for key accessibility elements; this will ensure the page headers are placed in header tags
          pageTitle: 'h1',
          pageSubtitle: 'h2'
        }
      },
      variants: [
        {
          props: { variant: 'pageTitle' },
          style: {
            fontSize: '2.2839rem',
            fontWeight: 'bold',
            borderLeft: '5px solid ' + themeBase.palette.secondary.main,
            paddingLeft: '10px'
          }
        },
        {
          props: { variant: 'pageSubtitle' },
          style: {
            borderLeft: '5px solid ' + themeBase.palette.tertiary.main,
            paddingLeft: '10px',
            paddingTop: '5px',
            paddingBottom: '5px',
            fontSize: '1.25rem',
            fontWeight: 'normal'
          }
        },
      ]
    }
  }
});

export default SparrowLight;