import { createTheme } from '@mui/material/styles';

//NOTE:
//Theme overrides / modification / customization adapted largely from:
//https://mui.com/material-ui/customization/palette/
//https://mui.com/material-ui/customization/theme-components/


//Perform module augmentation in order to add some custom properties to the theme
declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    pageTitle?: true
    pageSubtitle?: true
  }
}

declare module '@mui/material/styles' {
  interface Palette {
    tertiary: Palette['primary'];
  }

  interface PaletteOptions {
    tertiary?: PaletteOptions['primary'];
  }
}

//Instantiate theme; add in the custom tertiary color
const tertiaryMain = '#FFCD4B'
let themeBase = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#000033',
    },
    secondary: {
      main: '#FE7777',
    },
    tertiary: {
      main: tertiaryMain,
    },
    background: {
      default: '#000033',
      paper: '#ffffff',
    },
    text: {
      primary: '#000033',
    },
    shades: {
      primary: [
        '#ebebff',
        '#d6d6ff',
        '#adadff',
        '#8585ff',
        '#5c5cff',
        '#3333ff',
        '#0a0aff',
        '#0000e0',
        '#0000b8',
        '#00008f',
        '#000066',
        '#000033',
        '#000020',
        '#000014',
      ],
      secondary: [
        '#ffebeb',
        '#ffd6d6',
        '#ffc2c2',
        '#ffaeae',
        '#fe9a9a',
        '#fe7777',
        '#fe5d5d',
        '#fe3434',
        '#fe0b0b',
        '#df0101',
        '#b70101',
        '#8e0101',
        '#650101',
        '#3d0000',
        '#140000',
      ],
      tertiary: [
        '#fff9eb',
        '#fff3d6',
        '#ffe8ad',
        '#ffdc85',
        '#ffcd4b',
        '#ffc533',
        '#ffba0a',
        '#e0a100',
        '#b88400',
        '#8f6600',
        '#664900',
        '#3d2c00',
        '#140f00',
      ],
      supporting: {
        1: [
        '#c2ffff',
        '#85ffff',
        '#47ffff',
        '#00ffff',
        '#00cccc',
        '#008f8f',
        ],
        2: [
          
        ]
      }
    }
  }
})

//Update the theme with the autogenerated dark/light/contrasttext colors for the tertiary palette
themeBase = createTheme(themeBase, {
  palette: {
    tertiary: themeBase.palette.augmentColor({
      color: {
        main: tertiaryMain
      },
      name: 'tertiary'
    })
  }
})

//Add custom component styling
const SparrowLight = createTheme({
  palette: themeBase.palette,
  typography: {
    fontFamily: '"Karla", sans-serif',
    fontSize: 16,
  },
  components: {
    MuiTypography: {
      styleOverrides: {
        root:{
        }
      },
      defaultProps: {
        variantMapping: {
          //Add mapping for key accessibility elements; this will ensure the page headers are placed in header tags
          pageTitle: 'h1',
          pageSubtitle: 'h2'
        }
      },
      variants: [
        {
          props: {variant: 'pageTitle'},
          style: {
            fontSize: '2.2839rem',
            fontWeight: 'bold',
            borderLeft: '5px solid ' + themeBase.palette.secondary.main,
            paddingLeft: '10px'
          }
        },
        {
          props: {variant: 'pageSubtitle'},
          style: {
            borderLeft: '5px solid ' + themeBase.palette.tertiary.main,
            paddingLeft: '10px',
            paddingTop: '5px',
            paddingBottom: '5px',
            fontSize: '1.25rem',
            fontWeight: 'normal'
          }
        },
      ]
    }
  }
});

export default SparrowLight;