import { createTheme } from '@mui/material/styles';

//NOTE:
//Theme overrides / modification / customization adapted largely from:
//https://mui.com/material-ui/customization/palette/
//https://mui.com/material-ui/customization/theme-components/


//Perform module augmentation in order to add some custom properties to the theme
declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    pageTitle?: true
    pageSubtitle?: true
  }
}

declare module '@mui/material/styles' {
  interface Palette {
    tertiary: Palette['primary'];
  }

  interface PaletteOptions {
    tertiary?: PaletteOptions['primary'];
  }
}

//Instantiate theme; add in the custom tertiary color
const tertiaryMain = '#FF9F00'
let themeBase = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#E44B45',
    },
    secondary: {
      main: '#FFF700',
    },
    tertiary: {
      main: tertiaryMain,
    },
    background: {
      default: '#f9f9f9',
      paper: '#ffffff',
    },
    text: {
      primary: '#000033',
    },
    shades: {
      primary: [
        '#FCEEED',
        '#FADCDB',
        '#F5BAB8',
        '#F09794',
        '#EB7470',
        '#E44B45',
        '#E02F29',
        '#C4221C',
        '#A11C17',
        '#7D1512',
        '#590F0D',
        '#360908',
      ],
      secondary: [
        '#FFFEEB',
        '#FFFED6',
        '#FFFCAD',
        '#FFFB85',
        '#FFFA5C',
        '#FFF833',
        '#FFF700',
        '#E0D900',
        '#B8B100',
        '#8F8100',
        '#666300',
        '#3D3B00',
      ],
      tertiary: [
        '#FFF7EB',
        '#FFEFD6',
        '#FFE0AD',
        '#FFD085',
        '#FFC05C',
        '#FFB133',
        '#FF9F00',
        '#E08A00',
        '#B87100',
        '#85F800',
        '#663F00',
        '#3D2600',
      ],
      support: [
        '#EBEBFF',
        '#C2C2FF',
        '#999FF',
        '#7070FF',
        '#4747FF',
        '#8CEA48',
        '#74E524',
        '#61C918',
        '#50A413',
        '#2C5B0B',
        '#193306',
        '#091202',
      ]
    }
  }
})

//Update the theme with the autogenerated dark/light/contrasttext colors for the tertiary palette
themeBase = createTheme(themeBase, {
  palette: {
    tertiary: themeBase.palette.augmentColor({
      color: {
        main: tertiaryMain
      },
      name: 'tertiary'
    })
  }
})

//Add custom component styling
const SparrowLight = createTheme({
  palette: themeBase.palette,
  typography: {
    fontFamily: '"Karla", sans-serif',
    fontSize: 16,
  },
  components: {
    MuiTypography: {
      styleOverrides: {
        root:{
        }
      },
      defaultProps: {
        variantMapping: {
          //Add mapping for key accessibility elements; this will ensure the page headers are placed in header tags
          pageTitle: 'h1',
          pageSubtitle: 'h2'
        }
      },
      variants: [
        {
          props: {variant: 'pageTitle'},
          style: {
            fontSize: '2.2839rem',
            fontWeight: 'bold',
            borderLeft: '5px solid ' + themeBase.palette.secondary.main,
            paddingLeft: '10px'
          }
        },
        {
          props: {variant: 'pageSubtitle'},
          style: {
            borderLeft: '5px solid ' + themeBase.palette.tertiary.main,
            paddingLeft: '10px',
            paddingTop: '5px',
            paddingBottom: '5px',
            fontSize: '1.25rem',
            fontWeight: 'normal'
          }
        },
      ]
    }
  }
});

export default SparrowLight;