# Generated by Django 5.0 on 2024-01-12 00:04

import base.core.common.common_base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unnamed Alarm')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='AlarmDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='AlarmLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.DecimalField(decimal_places='2', max_digits='5')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='AlarmSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places='2', max_digits='5')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='AlarmTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='AlarmVibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='SoundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unnamed Alarm')),
                ('alarm_configuration_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.alarmconfiguration')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
        migrations.AddField(
            model_name='alarmconfiguration',
            name='alarm_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.alarmdevice'),
        ),
        migrations.AddField(
            model_name='alarmconfiguration',
            name='alarm_light_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.alarmlight'),
        ),
        migrations.AddField(
            model_name='alarmconfiguration',
            name='alarm_sound_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.alarmsound'),
        ),
        migrations.AddField(
            model_name='alarmconfiguration',
            name='alarm_time_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.alarmtime'),
        ),
        migrations.AddField(
            model_name='alarmconfiguration',
            name='alarm_vibration_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.alarmvibration'),
        ),
        migrations.AddField(
            model_name='alarmdevice',
            name='device_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.devicetype'),
        ),
        migrations.AddField(
            model_name='alarmsound',
            name='sound_source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparrow_rest.soundsource'),
        ),
    ]
