# Generated by Django 5.0 on 2023-12-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sparrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
