# Generated by Django 5.0 on 2023-12-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sparrow', '0003_dummymodelc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModelA',
        ),
        migrations.DeleteModel(
            name='DummyModelB',
        ),
        migrations.DeleteModel(
            name='DummyModelC',
        ),
    ]
