# Generated by Django 5.0 on 2023-12-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_sparrow', '0004_delete_dummymodela_delete_dummymodelb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModelD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
