# Generated by Django 5.0 on 2023-12-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sparrow', '0008_dummymodele'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DummyModelE',
            new_name='Alarm',
        ),
        migrations.DeleteModel(
            name='DummyModelD',
        ),
    ]
