# Generated by Django 5.0 on 2023-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sparrow', '0009_rename_dummymodele_alarm_delete_dummymodeld'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
