# Generated by Django 5.0 on 2023-12-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sparrow', '0010_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
