# Generated by Django 5.0 on 2024-01-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsound',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
