# Generated by Django 5.0 on 2024-02-23 14:31

import base.core.common.common_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_rest', '0003_alter_alarmlight_brightness'),
    ]

    operations = [
        migrations.CreateModel(
            name='LazyAlarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.core.common.common_base.CommonBase),
        ),
    ]
