# Generated by Django 5.0 on 2024-02-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_rest', '0004_lazyalarms'),
    ]

    operations = [
    ]
