# Generated by Django 3.2.8 on 2024-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyAlarm',
            fields=[
                ('user_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('alarms_json', models.TextField()),
            ],
        ),
    ]
