# Generated by Django 3.2.8 on 2024-03-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daybreakr_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lazyalarm',
            name='other',
        ),
    ]
