# Generated by Django 3.2.8 on 2024-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybreakr_data', '0002_auto_20240223_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='lazyalarm',
            name='userId',
            field=models.CharField(default='dummy_data ok_to_delete', max_length=512),
            preserve_default=False,
        ),
    ]
