# Generated by Django 3.2.8 on 2024-02-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daybreakr_data', '0003_lazyalarm_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lazyalarm',
            old_name='userId',
            new_name='user_id',
        ),
    ]
