# Generated by Django 3.2.8 on 2024-02-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybreakr_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LazyAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialization', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='LazyAlarms',
        ),
    ]
