# Generated by Django 5.0 on 2024-02-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lazyalarms',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='lazyalarms',
            name='user',
        ),
    ]
