import { createTheme } from '@mui/material/styles';

//NOTE:
//Theme overrides / modification / customization adapted largely from:
//https://mui.com/material-ui/customization/palette/
//https://mui.com/material-ui/customization/theme-components/


//Perform module augmentation in order to add some custom properties to the theme
declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    pageTitle?: true
    pageSubtitle?: true
  }
}

declare module '@mui/material/styles' {
  interface Palette {
    tertiary: Palette['primary'];
  }

  interface PaletteOptions {
    tertiary?: PaletteOptions['primary'];
  }
}

//Instantiate theme; add in the custom tertiary color
const tertiaryMain = '#1efdff'
let themeBase = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#000033',
    },
    secondary: {
      main: '#ff3399',
    },
    tertiary: {
      main: tertiaryMain,
    },
    background: {
      default: '#f9f9f9',
      paper: '#ffffff',
    },
    text: {
      primary: '#000033',
    },
  }
})

//Update the theme with the autogenerated dark/light/contrasttext colors for the tertiary palette
themeBase = createTheme(themeBase, {
  palette: {
    tertiary: themeBase.palette.augmentColor({
      color: {
        main: tertiaryMain
      },
      name: 'tertiary'
    })
  }
})

//Add custom component styling
const TrillliLight = createTheme({
  palette: themeBase.palette,
  typography: {
    fontFamily: '"Karla", sans-serif',
    fontSize: 16,
  },
  components: {
    MuiTypography: {
      styleOverrides: {
        root:{
        }
      },
      defaultProps: {
        variantMapping: {
          //Add mapping for key accessibility elements; this will ensure the page headers are placed in header tags
          pageTitle: 'h1',
          pageSubtitle: 'h2'
        }
      },
      variants: [
        {
          props: {variant: 'pageTitle'},
          style: {
            fontSize: '2.2839rem',
            fontWeight: 'bold',
            borderLeft: '5px solid ' + themeBase.palette.secondary.main,
            paddingLeft: '10px'
          }
        },
        {
          props: {variant: 'pageSubtitle'},
          style: {
            borderLeft: '5px solid ' + themeBase.palette.tertiary.main,
            paddingLeft: '10px',
            paddingTop: '5px',
            paddingBottom: '5px',
            fontSize: '1.25rem',
            fontWeight: 'normal'
          }
        },
      ]
    }
  }
});

export default TrillliLight;